CXX = clang++
BASE_FLAGS = -std=c++14 -Wall
TARGET = simulatore

SRCS = $(wildcard *.cpp)
OBJS = $(SRCS:.cpp=.o)

# ---------------------------------------------------------
# REGOLA DI DEFAULT (Scrivi solo "make")
# ---------------------------------------------------------
all: release

# ---------------------------------------------------------
# CONFIGURAZIONI
# ---------------------------------------------------------

# 1. RELEASE: Massima velocità
release: CXXFLAGS = $(BASE_FLAGS) -O3
release: clean_objs $(TARGET)

# 2. DEBUG: Stampe a schermo attive e zero ottimizzazione
debug: CXXFLAGS = $(BASE_FLAGS) -O0 -g -DDEBUG_ABILITATO
debug: clean_objs $(TARGET)_debug

# 3. SAMPLY (FIREFOX PROFILER): Ottimizzato, ma con simboli e frame pointer!
samply: CXXFLAGS = $(BASE_FLAGS) -O3 -g -fno-omit-frame-pointer -fno-inline
samply: clean_objs $(TARGET)_samply

# ---------------------------------------------------------
# COMPILAZIONE
# ---------------------------------------------------------
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

$(TARGET)_debug: $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET)_debug $(OBJS)

$(TARGET)_samply: $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET)_samply $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# ---------------------------------------------------------
# PULIZIA
# ---------------------------------------------------------
clean_objs:
	rm -f *.o

clean:
	rm -f *.o $(TARGET) $(TARGET)_debug $(TARGET)_samply